### ISSUE TITLE
Tool extract not working.

### ISSUE THREAD

**Issue by JokerDKha** [marcussacana/ThreeHousesSlave#2]
Hi thank you for hard work but seem like the tool is not work.
I want to extract 1 - scrdata.bin and repack it. Can you check what im doing wrong?
![image](https://user-images.githubusercontent.com/56380626/228112630-64bc9fb5-5b73-4bcb-b802-f64bb88ac153.png)

**Comment by marcussacana** [comment]
Tool is outdated, the next version might help with your problem but I didn't had time to test everything yet (thanks to RE4 remake, lol)

**Comment by marcussacana** [comment]
try the new version
