### ISSUE TITLE
Suporte ao texto da cutscene | Cutscene text support

### ISSUE THREAD

**Issue by Digote** [marcussacana/ThreeHousesSlave#3]
**Português do Brasil**

Existem alguns textos do jogo que aparentemente não possuem uma ferramenta ainda, como os textos das cutscenes. Até agora, verifiquei que há um modelo binário disponível para isso. Se você tiver interesse em implementá-lo, aqui estão algumas informações relevantes:

**Localização dos arquivos .bin das cutscenes:**
DATA1.bin\out\common\common\caption

**Link para o modelo binário:**
https://github.com/three-houses-research-team/010-binary-templates/blob/master/Captions.bt

Parabéns pela ferramenta! Já a testei e está funcionando perfeitamente.

______________________________________________________________________________________________________________________________________________

**English**

There are some game texts that seemingly lack a dedicated tool, such as the cutscene texts. So far, I've discovered that there is an available binary template for this purpose. If you're interested in implementing it, here is some relevant information:

**Location of the cutscene .bin files:**
DATA1.bin\out\common\common\caption

**Link to the binary template:**
https://github.com/three-houses-research-team/010-binary-templates/blob/master/Captions.bt

Congratulations on the tool! I've already tested it, and it's working perfectly.

**Comment by marcussacana** [comment]
O suporte a caption já está implementado 
https://github.com/marcussacana/ThreeHousesSlave/blob/4ea3a55defcc4b9e13acb1f2cf36d526c44fd9cf/Caption.cs#L14-L28
Ele deveria ter sido extraído com o nome _caption.txt/_caption.bin
https://github.com/marcussacana/ThreeHousesSlave/blob/4ea3a55defcc4b9e13acb1f2cf36d526c44fd9cf/Program.cs#L355
se o arquivo não existe na sua extração então pode ser algum bug.

**Comment by Digote** [comment]
Realmente estranho, ele faz o check, mas não extrai no meu caso, todos os outros arquivos
eu não tenho problema.
Vou tentar as versões 1.0 do jogo e no script em Python que você recomendou na descrição para extrair o DATA0.bin e DATA1.bin.
Até agora tentei somente com esse: https://raw.githubusercontent.com/three-houses-research-team/Throne-of-Knowledge/master/extractIndexNum.py

Obrigado pelo retorno.

**Comment by marcussacana** [comment]
Então ele renomeia pra _caption.bin mas não extrai o texto?

Eu não tenho mais o dump do jogo no PC, se quiser que eu teste me envie os arquivos caption que não estão sendo extraídos para que eu possa averiguar.

**Comment by Digote** [comment]
Claro, vou te mandar pasta do arquivos .bin da pasta caption dentro da pasta common, são vários arquivos que tem
todos os idiomas, se quiser verificar o inglês tem os exemplos dos arquivos 29830.bin e 29861.bin.

[caption.zip](https://github.com/marcussacana/ThreeHousesSlave/files/12095169/caption.zip)

**Comment by marcussacana** [comment]
Encontrei o problema, tente na nova versão.

**Comment by Digote** [comment]
Resolvido, muito obrigado pelo suporte.
Novamente, parabéns pela ferramenta, parece dar suporte a todos os textos.

![image](https://github.com/marcussacana/ThreeHousesSlave/assets/45742711/4ab2fdf2-0a7b-4ddf-8c5a-dd6a80522005)

**Comment by marcussacana** [comment]
Perfeito, que bom que funcionou, boa sorte com o projeto.
